### ISSUE TITLE
Cannot find module 'tslib'

### ISSUE THREAD

**Issue by Buszmen** [imjuni/create-ts-index#15]
I have a problem running version 1.10.0. When I run it, I get this error:
```
internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/user/.nvm/versions/node/v10.15.3/lib/node_modules/create-ts-index/dist/cti.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

I install the package globally, use NVM with node 10.15.3, npm 6.9.2.
Version 1.8.0 still works fine.

**Comment by imjuni** [comment]
@Buszmen TY feedback

I think that issue caused by devDependencies.

I will change dependencies tomorrow. (because, today npmjs.org not work!)

**Comment by imjuni** [comment]
@Buszmen I fix this issue. TY feedback.
